#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_PLAYER_OK 0
#define MUGSHOT_PLAYER_DETERMINED 1
#define MUGSHOT_PLAYER_SHOCK 2
#define MUGSHOT_PLAYER_CONFUSED 3
#define MUGSHOT_BLISSEY 4
#define MUGSHOT_BELLOSSUM 5
#define MUGSHOT_ROTOM 6
#define MUGSHOT_MAGNEZONE 7
#define MUGSHOT_JIRACHI_WORRIED 8
#define MUGSHOT_JIRACHI_OK 9
#define MUGSHOT_JIRACHI_HAPPY 10


#endif