#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_PLAYER_OK 0
#define MUGSHOT_PLAYER_DETERMINED 1
#define MUGSHOT_PLAYER_SHOCK 2
#define MUGSHOT_PLAYER_CONFUSED 3
#define MUGSHOT_BLISSEY 4
#define MUGSHOT_BELLOSSUM 5
#define MUGSHOT_ROTOM 6
#define MUGSHOT_MAGNEZONE 7
#define MUGSHOT_JIRACHI_WORRIED 8
#define MUGSHOT_JIRACHI_OK 9
#define MUGSHOT_JIRACHI_HAPPY 10
#define METER_O2_1 11
#define METER_O2_2 12
#define METER_O2_3 13
#define METER_O2_4 14
#define METER_O2_5 15
#define METER_O2_6 16
#define MUGSHOT_MAP_01 16
#define MUGSHOT_MAP_02 17
#define MUGSHOT_MAP_03 18
#define MUGSHOT_MAP_04 19
#define MUGSHOT_UNKNOWN 20
#define MUGSHOT_CAPTAIN_SAD 21

#endif