#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_PLAYER_OK 0
#define MUGSHOT_PLAYER_DETERMINED 1
#define MUGSHOT_PLAYER_SHOCK 2
#define MUGSHOT_PLAYER_CONFUSED 3
#define MUGSHOT_BLISSEY 4
#define MUGSHOT_BELLOSSUM 5
#define MUGSHOT_ROTOM 6
#define MUGSHOT_MAGNEZONE 7
#define MUGSHOT_JIRACHI_WORRIED 8
#define MUGSHOT_JIRACHI_OK 9
#define MUGSHOT_JIRACHI_HAPPY 10
#define METER_O2_1 11
#define METER_O2_2 12
#define METER_O2_3 13
#define METER_O2_4 14
#define METER_O2_5 15
#define METER_O2_6 16
#define METER_O2_GRASS1 17
#define METER_O2_GRASS2 18
#define METER_O2_GRASS3 19
#define METER_O2_GRASS4 20
#define METER_O2_GRASS5 21
#define METER_O2_GRASS6 22
#define MUGSHOT_MAP_01 23
#define MUGSHOT_MAP_02 24
#define MUGSHOT_MAP_03 25
#define MUGSHOT_MAP_04 26
#define MUGSHOT_UNKNOWN 27
#define MUGSHOT_CAPTAIN_SAD 28

#endif