gText_Birch_Welcome::
	.string "Hi! intro blurb!\p"
	.string "New paragraph!\p"
	.string "New paragraph with\n"
	.string "new line!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "1st line\n"
	.string "2nd line.\p"
	.string "Another 1st line,\n"
	.string "another 2nd line, but shift\l"
	.string "to 3rd line.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "$"
