gText_Birch_Welcome::
	.string "Why did I go become a space trucker? I\n"
	.string "said it was because it paid well, it\l"
	.string "was an opportunity to get experience,\l"
	.string "build reputation, bla, bla, bla.\l"
	.string "After having all this time to think,\l"
	.string "I'm not so sure that was the real reason\l"
	.string "I chose to spend the entire past year\l"
	.string "all alone.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Well, my trusty Magnezone and the rest\n"  
	.string "of my Pokemon crew are with me.\l"
	.string "Admittedly, it's not really the same.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "True, my trusty Magnezone and the rest\n"  
	.string "of my Pokemon crew are with me.\l"
	.string "Admittedly, it's not really the same.\p"
	.string "Though I'm heading home now, my contract\n"
	.string "renewed, so I can do it again...\l"
	.string "Another year... Surely it's a bad idea.\l"
	.string "But-\p"
	.string "...\n"
	.string "Huh?!\p"
	.string "My ship- Something is dragging us\n"
	.string "towards that nearby planet! What's\l"
	.string "going on?!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Oh, I forgot to say my name!$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "My name is...$"

gText_Birch_SoItsPlayer::
	.string "Yeah, I'm {PLAYER}{KUN}!$"

gText_Birch_YourePlayer::
	.string "This doesn't look good!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Everybody, brace for impact!\p"
	.string "$"
