# 1 "data/maps/Planet01_01/scripts.pory"

# 2 "data/maps/Planet01_01/scripts.pory"
Planet01_01_MapScripts::
# 3 "data/maps/Planet01_01/scripts.pory"
	.byte 0

Planet01_01_HintText01::
# 6 "data/maps/Planet01_01/scripts.pory"
	lock
# 7 "data/maps/Planet01_01/scripts.pory"
	msgbox Planet01_01_HintText01_Text_0
# 8 "data/maps/Planet01_01/scripts.pory"
	release
	end


Planet01_01_HintText01_Text_0:
# 7 "data/maps/Planet01_01/scripts.pory"
	.string "Some text says a thing!$"
